language: objective-c
before_script:
  - gem install xcpretty
script:
  - xcodebuild -scheme Isaac -destination platform='iOS Simulator',OS=7.1,name='iPhone Retina (4-inch)' clean test -sdk iphonesimulator | xcpretty -t -c; exit ${PIPESTATUS[0]}
